apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: jrichter-test-gitops
  description: This is GitOps manifest for jrichter-test   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: jrichter-test
    janus-idp.io/tekton: jrichter-test 
    backstage.io/kubernetes-id: jrichter-test 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:jrichter-test
